/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


-- -------------------------------------
-- Find total customers by countries
-- -------------------------------------

SELECT
    country,
    COUNT(DISTINCT customer_key) AS total_customers
FROM gold_dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- -------------------------------------
-- Find total customers by gender
-- -------------------------------------

SELECT
    gender,
    COUNT(DISTINCT customer_key) AS total_customers
FROM gold_dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- -------------------------------------
-- Find total products by category
-- -------------------------------------

SELECT
    category,
    COUNT(DISTINCT product_key) AS total_products
FROM gold_dim_products
GROUP BY category
ORDER BY total_products DESC;


-- ----------------------------------------------
-- What is the average costs in each category?
-- ----------------------------------------------

SELECT
    category,
    AVG(cost) AS average_cost
FROM gold_dim_products
GROUP BY category
ORDER BY average_cost DESC;


-- --------------------------------------------------------
-- What is the total revenue generated for each category?
-- --------------------------------------------------------

SELECT
    gdp.category,
    SUM(COALESCE(gfs.sales_amount, 0)) AS total_revenue
FROM gold_dim_products AS gdp
LEFT JOIN gold_fact_sales AS gfs
    ON gdp.product_key = gfs.product_key
GROUP BY gdp.category
ORDER BY total_revenue DESC;


-- --------------------------------------------------------
-- What is the total revenue generated by each customer?
-- --------------------------------------------------------

SELECT
    gdc.customer_key,
    gdc.first_name,
    gdc.last_name,
    SUM(gfs.sales_amount) AS total_revenue
FROM gold_dim_customers AS gdc
LEFT JOIN gold_fact_sales AS gfs
    ON gdc.customer_key = gfs.customer_key
GROUP BY 
    gdc.customer_key,
    gdc.first_name,
    gdc.last_name
ORDER BY total_revenue DESC;


-- ----------------------------------------------------------
-- What is the distribution of sold items across countries?
-- ----------------------------------------------------------

SELECT
    gdc.country,
    SUM(gfs.quantity) AS total_sold_items
FROM gold_dim_customers AS gdc
LEFT JOIN gold_fact_sales AS gfs
    ON gdc.customer_key = gfs.customer_key
GROUP BY gdc.country
ORDER BY total_sold_items DESC;
